spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cryptocurrency-watcher-kotlin
      username: root
      password: root
      authentication-database: admin

  graphql:
    graphiql:
      path: /graphiql
      enabled: true

bot:
  name: CryptocurrencyWatcherBot
  token: 5455319301:AAHjNcR1gvBZULYC7eTdL0RDTCHqQJts_cE
